import { District } from '@/types/atlas'

// v3 — Atlas 1.1: all opportunities executable, scouted protocols added
export const DISTRICTS: District[] = [
  {
    id: 'income',
    name: 'Income District',
    color: '#34D186',
    position: [-4, 0, -2],
    description: 'Treasury-backed yield. Stable passive income.',
    opportunities: [
      {
        id: 'usdy',
        name: 'USDY',
        district: 'income',
        apy: 5.1,
        risk: 'low',
        minCapital: 10,
        description: 'Ondo US Dollar Yield — tokenized US Treasury yield on-chain. Backed by short-term T-bills. Redeemable 1:1 for USD.',
        protocol: 'Ondo Finance',
        asset: 'USDY',
        mantleNative: true,
      },
      {
        id: 'musd',
        name: 'mUSD',
        district: 'income',
        apy: 4.8,
        risk: 'low',
        minCapital: 10,
        description: 'Mantle USD — native yield-bearing stablecoin. Yield sourced from Mantle treasury reserves and protocol revenue.',
        protocol: 'Mantle',
        asset: 'mUSD',
        mantleNative: true,
      },
      {
        id: 'aave-usdt',
        name: 'Aave v3 USDT',
        district: 'income',
        apy: 6.8,
        risk: 'low',
        minCapital: 10,
        description: 'Supply USDT to Aave v3 on Mantle. Earn variable lending interest from borrowers. Battle-tested protocol, billions in TVL.',
        protocol: 'Aave v3',
        asset: 'USDT',
        mantleNative: true,
      },
    ],
  },
  {
    id: 'staking',
    name: 'Staking District',
    color: '#3B82F6',
    position: [4, 0, -2],
    description: 'ETH liquid staking and validator yield.',
    opportunities: [
      {
        id: 'meth',
        name: 'mETH',
        district: 'staking',
        apy: 3.8,
        risk: 'low',
        minCapital: 0.01,
        description: 'Mantle liquid staked ETH. Deposit ETH, receive mETH that auto-compounds Ethereum validator rewards. Fully liquid.',
        protocol: 'Mantle LSP',
        asset: 'mETH',
        mantleNative: true,
      },
      {
        id: 'mnt-staking',
        name: 'MNT Native Staking',
        district: 'staking',
        apy: 2.8,
        risk: 'low',
        minCapital: 1,
        description: 'Stake MNT directly with Mantle validators. Lowest risk in the ecosystem — no smart contract exposure beyond the core protocol.',
        protocol: 'Mantle Network',
        asset: 'MNT',
        mantleNative: true,
      },
    ],
  },
  {
    id: 'growth',
    name: 'Growth District',
    color: '#A855F7',
    position: [0, 0, 4],
    description: 'Ecosystem growth. Higher yield, accepts more volatility.',
    opportunities: [
      {
        id: 'mnt-lp',
        name: 'MNT / USDT LP',
        district: 'growth',
        apy: 14.2,
        risk: 'medium',
        minCapital: 50,
        description: 'Provide liquidity to the MNT/USDT pool on Agni Finance. Earn trading fees + MNT rewards. Subject to impermanent loss.',
        protocol: 'Agni Finance',
        asset: 'MNT-USDT LP',
        mantleNative: true,
      },
      {
        id: 'lendle-mnt',
        name: 'MNT Lending',
        district: 'growth',
        apy: 8.6,
        risk: 'medium',
        minCapital: 20,
        description: 'Supply MNT to Lendle lending markets. Earn variable interest from borrowers. Largest money market on Mantle.',
        protocol: 'Lendle',
        asset: 'MNT',
        mantleNative: true,
      },
      {
        id: 'clearpool-usdt',
        name: 'Clearpool USDT',
        district: 'growth',
        apy: 12.6,
        risk: 'medium',
        minCapital: 25,
        description: 'Institutional lending via Clearpool. Earn yield from permissioned borrowers with credit risk assessment. Higher yield, institutional demand-driven.',
        protocol: 'Clearpool',
        asset: 'USDT',
        mantleNative: true,
      },
    ],
  },
  {
    id: 'treasury',
    name: 'Treasury District',
    color: '#F59E0B',
    position: [-4, 0, 3],
    description: 'Institutional-grade capital. Long-term preservation with institutional backing.',
    opportunities: [
      {
        id: 'mantle-treasury',
        name: 'Mantle Treasury Index',
        district: 'treasury',
        apy: 6.2,
        risk: 'low',
        minCapital: 500,
        description: 'Diversified exposure to Mantle ecosystem treasury assets — mETH, mUSD, and MNT. Rebalances quarterly. Institutional-grade.',
        protocol: 'Mantle Finance',
        asset: 'MTI',
        mantleNative: true,
      },
      {
        id: 'usdy-vault',
        name: 'USDY Compounding Vault',
        district: 'treasury',
        apy: 5.4,
        risk: 'low',
        minCapital: 100,
        description: 'Auto-compounding USDY vault. Yield is reinvested daily. Set it and forget it — capital preservation with steady growth.',
        protocol: 'Ondo Finance',
        asset: 'USDY',
        mantleNative: true,
      },
    ],
  },
  {
    id: 'emerging',
    name: 'Emerging District',
    color: '#F97316',
    position: [4, 0, 3],
    description: 'New protocols. Early-stage yield. Higher upside, higher risk.',
    opportunities: [
      {
        id: 'init-capital',
        name: 'INIT Capital',
        district: 'emerging',
        apy: 18.5,
        risk: 'high',
        minCapital: 25,
        description: 'Liquidity hook protocol on Mantle. Deploy capital into composable lending positions. High APY from early incentives.',
        protocol: 'INIT Capital',
        asset: 'MNT',
        mantleNative: true,
      },
      {
        id: 'cleopatra',
        name: 'Cleopatra Exchange',
        district: 'emerging',
        apy: 22.0,
        risk: 'high',
        minCapital: 50,
        description: 'veNFT-based DEX on Mantle. Lock MNT for veMNT, earn protocol fees and boosted emissions. High yield, token-emission risk.',
        protocol: 'Cleopatra',
        asset: 'MNT',
        mantleNative: true,
      },
      {
        id: 'fluxion',
        name: 'Fluxion Network',
        district: 'emerging',
        apy: 15.0,
        risk: 'high',
        minCapital: 20,
        description: 'Cross-chain yield aggregator on Mantle. Routes capital to the highest-yielding vaults across protocols. Early-stage with high incentives.',
        protocol: 'Fluxion',
        asset: 'USDC',
        mantleNative: true,
      },
    ],
  },
  {
    id: 'safety',
    name: 'Safety District',
    color: '#06B6D4',
    position: [0, 0, -5],
    description: 'Capital preservation first. Ultra-low risk. Sleep well.',
    opportunities: [
      {
        id: 'usdy-safety',
        name: 'USDY Safe Hold',
        district: 'safety',
        apy: 5.1,
        risk: 'low',
        minCapital: 10,
        description: 'Hold USDY — dollar-stable, T-bill backed, yield-bearing. The DeFi equivalent of a savings account with no lock-up.',
        protocol: 'Ondo Finance',
        asset: 'USDY',
        mantleNative: true,
      },
      {
        id: 'circuit-eth',
        name: 'Circuit Staked ETH',
        district: 'safety',
        apy: 3.5,
        risk: 'low',
        minCapital: 10,
        description: 'ETH liquid staking via Circuit Protocol. Conservative staking strategy with lower risk than direct validator staking.',
        protocol: 'Circuit Protocol',
        asset: 'ETH',
        mantleNative: true,
      },
    ],
  },
]

export const getDistrict = (id: string) => DISTRICTS.find(d => d.id === id)
